feat: 更新 fn-open-vm-tools 和 fn-qemu-ga 版本至 1.0.7，优化启动和停止过程的日志记录

diff --git a/fn-open-vm-tools/cmd/main b/fn-open-vm-tools/cmd/main
--- a/fn-open-vm-tools/cmd/main
+++ b/fn-open-vm-tools/cmd/main
@@ -3,50 +3,54 @@
 LOG_FILE="${TRIM_PKGVAR}/info.log"
 PID_FILE="${TRIM_PKGVAR}/app.pid"
 
-# write the command to start your program here 
+# write the command to start your program here
 CMD=""
 
 log_msg() {
-    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
+  echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >>${LOG_FILE}
 }
 
 start_process() {
-    if status; then
-        return 0
-    fi
+  if status; then
+    return 0
+  fi
 
-    log_msg "Starting process ..."
-    systemctl start open-vm-tools.service >> ${LOG_FILE} 2>&1
+  log_msg "Starting process ..."
+  systemctl start open-vm-tools.service >>${LOG_FILE} 2>&1
 }
 
 stop_process() {
-    log_msg "Stopping process ..."
+  log_msg "Stopping process ..."
 
-    systemctl stop open-vm-tools.service >> ${LOG_FILE} 2>&1
+  systemctl stop open-vm-tools.service >>${LOG_FILE} 2>&1
 }
 
 status() {
-    systemctl status open-vm-tools.service
+  systemctl status open-vm-tools.service
 }
 
 case $1 in
-start)
+  start)
     # run start command. exit 0 if success, exit 1 if failed
+    if [ ! -e /dev/vmci ]; then
+      echo "VMware VMCI device not found. Cannot start." >$TRIM_TEMP_LOGFILE
+      exit 1
+    fi
     start_process
     ;;
-stop)
+  stop)
     # run stop command. exit 0 if success, exit 1 if failed
     stop_process
     ;;
-status)
+  status)
     # check application status command. exit 0 if running, exit 3 if not running
-    if status; then 
-        exit 0
-    else 
-        exit 3
+    if status; then
+      exit 0
+    else
+      exit 3
     fi
     ;;
-*)
+  *)
     exit 1
     ;;
 esac
