feat: 重构 fn-ntfs3, 添加 Docker 支持以减小对系统的影响

diff --git a/fn-ntfs3/cmd/install_callback b/fn-ntfs3/cmd/install_callback
--- a/fn-ntfs3/cmd/install_callback
+++ b/fn-ntfs3/cmd/install_callback
@@ -2,4 +2,53 @@
 
 ### This script is called after the user installs the application.
 
-$(dirname $0)/build >$TRIM_TEMP_LOGFILE 2>&1
+KVER="$(uname -r)"
+SVER="$(echo "${KVER}" | cut -d'.' -f1,2)"
+
+# Prepare build environment
+if [ ! -f "${TRIM_APPDEST}/server/src/${SVER}/Makefile" ]; then
+  echo "Source code for kernel version ${SVER} not found." >$TRIM_TEMP_LOGFILE
+  exit 1
+fi
+
+# Build the module
+$(dirname $0)/docker_make.sh --pkgs build-essential bc -- \
+  make -C /lib/modules/${KVER}/build M="${TRIM_APPDEST}/server/src/${SVER}" CONFIG_NTFS3_FS=m CONFIG_NTFS3_LZX_XPRESS=y modules 2>$TRIM_TEMP_LOGFILE
+[ $? -ne 0 ] && exit 1
+
+if [ ! -f "${TRIM_APPDEST}/server/src/${SVER}/ntfs3.ko" ]; then
+  echo "Build ntfs3 module failed." >$TRIM_TEMP_LOGFILE
+  exit 1
+fi
+
+# Install the module
+mkdir -p /usr/lib/modules/${KVER}/updates/fs
+rm -f /usr/lib/modules/${KVER}/updates/fs/ntfs3.ko 2>/dev/null || true
+cp -vpf "${TRIM_APPDEST}/server/src/${SVER}/ntfs3.ko" /usr/lib/modules/${KVER}/updates/fs/ntfs3.ko
+if [ $? -ne 0 ]; then
+  echo "Install ntfs3 module failed." >$TRIM_TEMP_LOGFILE
+  exit 1
+fi
+
+depmod -a || true
+echo ntfs3 >/etc/modules-load.d/ntfs3.conf
+if [ $? -ne 0 ]; then
+  echo "Update modules load failed." >$TRIM_TEMP_LOGFILE
+  exit 1
+fi
+
+# Restart systemd-modules-load.service to load the module
+systemctl restart systemd-modules-load.service
+if [ $? -ne 0 ]; then
+  echo "Restart systemd-modules-load.service failed." >$TRIM_TEMP_LOGFILE
+  exit 1
+fi
+
+# Replace the mount.ntfs symlink to point to mount.ntfs3
+rm -f /usr/sbin/mount.ntfs && echo -e '#!/bin/sh\nmount -t ntfs3 "$@"' >/usr/sbin/mount.ntfs && chmod a+x /usr/sbin/mount.ntfs
+if [ $? -ne 0 ]; then
+  echo "Replace mount.ntfs symlink failed." >$TRIM_TEMP_LOGFILE
+  exit 1
+fi
+
+exit 0
