feat: 更新 Build，支持自定义构建脚本

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -43,30 +43,35 @@ jobs:
 
             # ./fnpack create ${APP} --without-ui true  # 如果不需要 UI, 可以启用此行
 
-            APPNAME=$(grep '^appname' "$APP/manifest" | awk -F= '{print $2}' | xargs)
-            VERSION=$(grep '^version' "$APP/manifest" | awk -F= '{print $2}' | xargs)
-            DESC=$(grep '^desc' "$APP/manifest" | awk -F= '{print $2}' | xargs)
-            PLATFORM=$(grep '^platform' "$APP/manifest" | awk -F= '{print $2}' | xargs)
+            APPNAME=$(grep '^appname' "${APP}/manifest" | awk -F= '{print $2}' | xargs)
+            VERSION=$(grep '^version' "${APP}/manifest" | awk -F= '{print $2}' | xargs)
+            DESC=$(grep '^desc' "${APP}/manifest" | awk -F= '{print $2}' | xargs)
+            PLATFORM=$(grep '^platform' "${APP}/manifest" | awk -F= '{print $2}' | xargs)
 
             echo "| ${APPNAME} | v${VERSION} | ${PLATFORM} | ${DESC} |" >> apps-list.md
 
-            ./fnpack build --directory "${APP}"
-            mv -f "${APPNAME}.fpk" "${APPNAME}_${PLATFORM}_v${VERSION}.fpk"
-
-            SIZE=$(stat -c%s "${APPNAME}_${PLATFORM}_v${VERSION}.fpk" 2>/dev/null | awk '{printf "%10.3f",$1/1024/1024}')
-            NAME=$(grep '^display_name' "$APP/manifest" | awk -F= '{print $2}' | xargs)
-            TYPE=$(grep '^install_type' "$APP/manifest" | awk -F= '{print $2}' | xargs)
-            APPS+=("\"${APP}\": {\"display_name\": \"${NAME}\", \"desc\": \"${DESC}\", \"labels\": \"工具\", \"version\": \"${VERSION}\", \"download_url\": \"https://github.com/${REPO}/releases/download/${TAG}/${APPNAME}_${PLATFORM}_v${VERSION}.fpk\", \"author\": \"Ing\", \"author_url\": \"https://github.com/${REPO}\", \"bug_report_url\": \"https://github.com/${REPO}/issues\", \"install_type\": \"${TYPE}\", \"size\": \"${SIZE}\", \"history\": {\"v${VERSION}\": \"Initial release of ${APPNAME} package.\"}}")
-          
-            # 多架构临时对策
-            if [ "${PLATFORM}" = "all" ]; then
-              for P in x86 arm; do
-                sed -i "s/= all/= ${P}/" "${APP}/manifest"
-                ./fnpack build --directory "${APP}"
-                mv -f "${APPNAME}.fpk" "${APPNAME}_${P}_v${VERSION}.fpk"
-                sed -i "s/= ${P}/= all/" "${APP}/manifest"
-              done
+            if [ -f "${APP}/build.sh" ]; then
+              chmod +x "$(realpath "${APP}")/build.sh"
+              "$(realpath "${APP}")/build.sh"
+              [ $? -ne 0 ] && echo "Build script failed for ${APP}" && exit 1
+            else
+              ./fnpack build --directory "${APP}"
+              mv -f "${APPNAME}.fpk" "${APPNAME}_${PLATFORM}_v${VERSION}.fpk"
+              # 多架构临时对策
+              if [ "${PLATFORM}" = "all" ]; then
+                for P in x86 arm; do
+                  sed -i "s/= all/= ${P}/" "${APP}/manifest"
+                  ./fnpack build --directory "${APP}"
+                  mv -f "${APPNAME}.fpk" "${APPNAME}_${P}_v${VERSION}.fpk"
+                  sed -i "s/= ${P}/= all/" "${APP}/manifest"
+                done
+              fi
             fi
+            SIZE=$(stat -c%s "${APPNAME}_${PLATFORM}_v${VERSION}.fpk" 2>/dev/null | awk '{printf "%10.3f",$1/1024/1024}')
+            NAME=$(grep '^display_name' "${APP}/manifest" | awk -F= '{print $2}' | xargs)
+            TYPE=$(grep '^install_type' "${APP}/manifest" | awk -F= '{print $2}' | xargs)
+            APPS+=("\"${APP}\": {\"display_name\": \"${NAME}\", \"desc\": \"${DESC}\", \"labels\": \"工具\", \"version\": \"${VERSION}\", \"download_url\": \"https://github.com/${REPO}/releases/download/${TAG}/${APPNAME}_${PLATFORM}_v${VERSION}.fpk\", \"author\": \"Ing\", \"author_url\": \"https://github.com/${REPO}\", \"bug_report_url\": \"https://github.com/${REPO}/issues\", \"install_type\": \"${TYPE}\", \"size\": \"${SIZE}\", \"history\": {\"v${VERSION}\": \"Initial release of ${APPNAME} package.\"}}")
+
           done
 
           echo "" >> apps-list.md
@@ -99,9 +104,9 @@ jobs:
 
       - name: Release
         if: success() && !cancelled()
-        uses: ncipollo/release-action@v1
+        uses: softprops/action-gh-release@v2
         with:
-          token: ${{ secrets.RRORG }}
-          tag: ${{ env.TAG }}
-          artifacts: "*.fpk"
-          bodyFile: "apps-list.md"
+          body_path: "apps-list.md"
+          tag_name: ${{ env.TAG }}
+          files: |
+            *.fpk
